### ISSUE TITLE
Verifiable Presentation Actor correction

### ISSUE THREAD

**Issue by sumapnair-ibm** [TalaoDAO/hedera-vc-api#4]
The readme located at https://github.com/TalaoDAO/hedera-vc-api outlines the REST endpoints, and one of them is listed as follows:
"#4: [Issuer] Issue a Verifiable Presentation."
However, this appears to be a discrepancy; typically, issuing a Verifiable Presentation is the holder's responsibility. Any request for a Presentation should originate from the verifier, and the presentation itself should be provided by the holder. It's unclear why this task is attributed to the issuer. The vc-api specification also reflects the expected roles correctly, as shown in the image from the spec below.

![image](https://github.com/TalaoDAO/hedera-vc-api/assets/54110776/fe31dfaf-ade0-487c-ac77-b0a6537e0029)

Is this discrepancy a typographical mistake or an error in implementation? Could this be corrected, please?

**Comment by podefr** [comment]
I believe it should say `4. [holder] prove a Presentation`. would you agree?

**Comment by sumapnair-ibm** [comment]
I agree. Can you also please confirm the impl.? See #5 for the reason for my concern.

**Comment by podefr** [comment]
I understand the 2 issues are related. It's not however an implementation issue, rather a configuration issue.
I believe the example for proving a presentation was issued by a VC API configured as the issuer instead of the holder. I'll reply in the other discussion

**Comment by podefr** [comment]
@sumapnair-ibm  please verify if this PR solves this issue: https://github.com/TalaoDAO/hedera-vc-api/pull/6
