### ISSUE TITLE
Signing a Presentation

### ISSUE THREAD

**Issue by sumapnair-ibm** [TalaoDAO/hedera-vc-api#5]
Ref: #4 
I'm somewhat puzzled by a specific entry in the readme:
"#5: [Verifier] Verify a Presentation issued by a did:hedera."
This entry seems to suggest that the issuer is the one signing the VP proof, which the verifier then verifies (considering the context of item #4).

In the example at [https://github.com/TalaoDAO/hedera-vc-api/blob/main/examples/03-issue-verify-VP.md](https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_TalaoDAO_hedera-2Dvc-2Dapi_blob_main_examples_03-2Dissue-2Dverify-2DVP.md&d=DwMFaQ&c=jf_iaSHvJObTbx-siA1ZOg&r=SZHREh3pL8SBf8XBrwNLIesjrgSg-15sofpRBtDrpEk&m=-IhgHSpH8Be7rqbrhyshahxUkI7M7XX0yfaXWDHKTYMhQ9Vra5pFJDrmqQeIPW04&s=uY8YpqrcAY7fVKznPXXAlS5AXYodZUxP4xkXZA3QUmw&e=), the VP proof under the section "And we'll verify it now:" shows the issuer’s did as the verificationMethod in both the VC's and VP's proof sections, which seems incorrect. The VP should be signed by the holder, not the issuer.

Could you please confirm whether this is just a copy-paste error or an actual issue in the implementation? Either way, can this be rectified, please?

**Comment by podefr** [comment]
I believe that the example was generated while the VC API was still configured with the Issuer account instead of the holder account. The server can only be configured as one actor at a time. I'll use another account as the holder account and will regenerate a new example, which should address the issue. thanks for pointing it out

**Comment by sumapnair-ibm** [comment]
sounds good.

**Comment by podefr** [comment]
@sumapnair-ibm  please verify if this PR solves this issue: https://github.com/TalaoDAO/hedera-vc-api/pull/6

also note, it seems that your concern raised an actual issue with this library I'm using (`https://www.npmjs.com/package/@digitalbazaar/vc`) where the `verify` method for presentations assumes that the presenter is also the credential's issuer. Basically, the verificationMethod for the Presentation must be the same as each Credential's verificationMethod, as they both rely on the same verification `suite` being configured.

To address this issue, as seen in the PR, I'm validating each credential individually, then verifying the Presentation's enveloppe, and if all are valid, then the Presentation must be valid.

Hope this addresses the issue

**Comment by podefr** [comment]
I'm merging this one, please create a new one if this isn't sufficient
