### ISSUE TITLE
Different 400 message when Credential is revoked.

### ISSUE THREAD

**Issue by Reccetech** [TalaoDAO/hedera-vc-api#8]
When you do Verification of a revoked Verifiable Credential - if the credential is properly revoked then you'll get a 400 "message": "Invalid Input!"

However this is the same message I seem to get when there is any issues with a credential one is attempting to verify. Therefore one cannot distinguish from the response if the credential is revoked or there is maybe a format issue with the credential. 

Is it possible to create a specific response message if a credential is revoked?

**Comment by podefr** [comment]
this is good feedback and I agree, but this is currently as per the specifications:

https://w3c-ccg.github.io/vc-api/#verify-credential 

this issue should probably discussed with the working group, what do you think?

**Comment by Reccetech** [comment]
Sounds good.
